# Not a .NET project, we build PDSim in the install step instead
build: false

# Taken from SpiceyPy with some modification
environment:
  global:
      WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\windows_sdk.cmd"
  TWINE_PASSWORD:
    secure: JjNZdPH3xLhd2obfOsF5YA==
  TWINE_USERNAME: belli

  matrix:
      - PYTHON: "C:\\Python36-x64"
        PYTHON_VERSION: "3.6.x"
        ARCH: "64"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp36"
      - PYTHON: "C:\\Python37-x64"
        PYTHON_VERSION: "3.7.x"
        ARCH: "64"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp37"

platform:
    -x64

install:
  # Log out the python version just so we know it
  - ECHO "%PYTHON_VERSION%"

  # update path to use installed pip
  - set PATH=%PYTHON%\\scripts;%PATH%

  # Download things we absolutely need
  - pip install wheel twine six numpy wxpython cython h5py matplotlib
  - pip install --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp

  # Now install PDSim
  - "%PYTHON%/python setup.py install"

  - ECHO "Installed PDSim"

test_script:
    - "cd examples && %PYTHON%/python simple_example.py"
    - "%PYTHON%/python -c \"import PDSim; print(PDSim.__git_revision__)\""

after_test:
  - ECHO "DONE!"
  - ECHO "BUILDING WHEELS..."
  - cd ..
  - "%PYTHON%/python setup.py bdist_wheel --plat-name=%PLAT_NAME%"
  
artifacts:
  - path: dist\*
    name: pypi_artifacts

# Thanks to https://github.com/AndrewAnnex/SpiceyPy/blob/master/appveyor.yml
deploy_script:
  - echo "Starting Artifact Deployment"
  # upload to pypi for windows
  - set PATH=%BK_PATH%
  - set HOME=%USERPROFILE%
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true") { Invoke-Expression "twine upload --verbose --skip-existing dist/*.whl" 2>$null } Else { write-output "Not on a tag, won't deploy to pypi"}
  - echo "Finished Artifact Deployment to PYPI"
